[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  VITE_ADMIN_ACCESS_TOKEN = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
